// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAywIieP-UgkKReGsJfZQHiNXu0ef6zHM0',
    appId: '1:264846464929:android:282b645d627c94d8ce9de0',
    messagingSenderId: '264846464929',
    projectId: 'spraypay-frankdroid',
    storageBucket: 'spraypay-frankdroid.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-5CAcbnouoX7C0WFe5VEUqg7m7NWLF8Y',
    appId: '1:264846464929:ios:6e2ecd0d84d26dc6ce9de0',
    messagingSenderId: '264846464929',
    projectId: 'spraypay-frankdroid',
    storageBucket: 'spraypay-frankdroid.firebasestorage.app',
    androidClientId: '264846464929-ohfabnln6ki98jgc2ddmho5037cesqql.apps.googleusercontent.com',
    iosClientId: '264846464929-uem5d3m3c5mlu2d7ku29r1kivngi6ldj.apps.googleusercontent.com',
    iosBundleId: 'com.example.spray',
  );

}